// Generated by ReScript, PLEASE EDIT WITH CARE


var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

window.count = 0;

var counterText = document.getElementById("count");

function updateCount(steps) {
  window.count = steps + window.count | 0;
  
}

function updateCounterCSS(param) {
  if (window.count > 0) {
    counterText.className = "count count-positive";
  } else if (window.count < 0) {
    counterText.className = "count count-negative";
  } else {
    counterText.className = "count count-zero";
  }
  
}

function renderCountView(param) {
  counterText.innerText = "Count is " + window.count;
  
}

function renderView(steps) {
  updateCount(steps);
  updateCounterCSS(undefined);
  return renderCountView(undefined);
}

function plusOne(param) {
  return renderView(1);
}

function minusOne(param) {
  return renderView(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  counterText ,
  updateCount ,
  updateCounterCSS ,
  renderCountView ,
  renderView ,
  plusOne ,
  minusOne ,
  
}
/* plusButton Not a pure module */
